title: <p align="center">Adharsh Belagapu </p>
logo: /assets/img/logo.png
description: Certified Robotics Solution Designer, Senior Developer.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
